### PR TITLE
Connect peers via multiple ports.

### PR DESCRIPTION
**Pull request by mo-esmp**
Trying to connect to the peer from 10 different ports at the same time.

### CODE REVIEW

**Comment by knocte** [comment]
Hey @mo-esmp this looks like good work but we'll do a thorough review before merging. Please don't get de-motivated by the review because I'm going to pay you anyway for all the extra time that is needed until this can be merged :)

First thing I would like to ask you, which maybe sounds a bit surprising, is too make 1 push per commit. You may ask why? Well, the reason is so that we have CI build status of each commit. And again you may ask why? Well, because it's not good to break the build between commits (even if I can see that the build of the last commit is green). And you may ask why? Well, because when you're doing git bisections (e.g. to look for when exactly a bug was introduced in the past), if the build breaks in some commit then it cannot be bisected/tested.

So I think doing a push per commit is so important that I even wrote a tool for that, it's here:
https://github.com/nblockchain/fsx/blob/master/Tools/gitPush1by1.fsx

You can run it this way: https://stackoverflow.com/a/58121483/544947
And the arguments you can use are: `origin 15` (the remote and the number of commits)

**Comment by knocte** [comment]
Great thanks for pushing one by one.

As you can see, a couple of commits have the build broken:

https://github.com/mo-esmp/p2pcopy/commits/master

You could fix this with an interactive git rebase, squashing some commits. But to be honest I would prefer if you could do something else: can you create another branch, starting again from a6ee31f0b5ccd02589efa79c00bcc2f72a73174a but only including relevant commits? Otherwise, this PR is impossible to review because there's refactoring (changes that don't change behaviour) mixed with commits that have change of behaviour.

I'll make a list below of the commits I would prefer you include in this new PR:

- [ ] Fix code style and remove redundant codes. -> refactoring, so let's leave it for a 2nd PR
- [ ] Move connecting to peer to separate class. -> refactoring, so let's leave it for a 2nd PR
- [ ] Move connecting to stun server to separate class. -> refactoring, so let's leave it for a 2nd PR
- [x] Make Main method async and remove extra codes. -> good (except the removal of "extra codes")
- [ ] Fix StunServerConnector code style. -> refactoring, so let's leave it for a 2nd PR
- [x] Connect to peer multiple ports. -> good, change of behaviour
- [x] Close sockets at end of operation. -> good, change of behaviour
- [ ] Add using static System.Console. -> refactoring, so let's leave it for a 2nd PR
- [x] Fix internet sleep time across tasks. -> change of behaviour (but please don't change existing lines to use `var`, only use `var` in new lines of code; and don't add the `private` modifier)
- [x] Remove extra codes. -> this was a cleanup of previous commit, let's include these changes in previous commit
- [x] Replace goto -:( -> good, goto is evil
- [x] Replace Task.WhenAll with Task.WithAny. -> good, change of behaviour
- [x] ThrowIfCancellationRequested after connect method -> good, change of behaviour
- [x] urgh. -> this was a cleanup of previous commit, let's include these changes in previous commit
- [ ] dummy commit. -> no need now

Hope that it's clear what I'm asking! If not, let me know :)

**Comment by knocte** [comment]
I guess you didn't mean to close the PR?

**Comment by mo-esmp** [comment]
I reset my fork to the commit you just mentioned, that's why PR is closed.

**Comment by knocte** [comment]
That's fine, let's reopen it?

**Comment by mo-esmp** [comment]
It can't be reopened because those commits no longer exist.

**Comment by knocte** [comment]
I see new commits here https://github.com/mo-esmp/p2pcopy/commits/master

**Comment by mo-esmp** [comment]
I sent commits as a new PR https://github.com/nblockchain/p2pcopy/pull/2

**Pull request closed without merging**
